const pullRequest = {
  url: 'https://api.github.com/repos/ansible/ansible/issues/16510',
  repository_url: 'https://api.github.com/repos/ansible/ansible',
  labels_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/labels{/name}',
  comments_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/comments',
  events_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/events',
  html_url: 'https://github.com/ansible/ansible/pull/16510',
  id: 163031382,
  number: 16510,
  title: 'Adds docker-machine module-utils',
  user: {
    login: 'jgrowl',
    id: 90719,
    avatar_url: 'https://avatars.githubusercontent.com/u/90719?v=3',
    gravatar_id: '',
    url: 'https://api.github.com/users/jgrowl',
    html_url: 'https://github.com/jgrowl',
    followers_url: 'https://api.github.com/users/jgrowl/followers',
    following_url: 'https://api.github.com/users/jgrowl/following{/other_user}',
    gists_url: 'https://api.github.com/users/jgrowl/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jgrowl/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jgrowl/subscriptions',
    organizations_url: 'https://api.github.com/users/jgrowl/orgs',
    repos_url: 'https://api.github.com/users/jgrowl/repos',
    events_url: 'https://api.github.com/users/jgrowl/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jgrowl/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [
    {
      url: 'https://api.github.com/repos/ansible/ansible/labels/feature_pull_request',
      name: 'feature_pull_request',
      color: '006b75',
    },
    {
      url: 'https://api.github.com/repos/ansible/ansible/labels/new_plugin',
      name: 'new_plugin',
      color: 'bfe5bf',
    },
  ],
  state: 'open',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: {
    url: 'https://api.github.com/repos/ansible/ansible/milestones/8',
    html_url: 'https://github.com/ansible/ansible/milestones/2.2.0',
    labels_url: 'https://api.github.com/repos/ansible/ansible/milestones/8/labels',
    id: 1702615,
    number: 8,
    title: '2.2.0',
    description: '',
    creator: {
      login: 'sivel',
      id: 39340,
      avatar_url: 'https://avatars.githubusercontent.com/u/39340?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/sivel',
      html_url: 'https://github.com/sivel',
      followers_url: 'https://api.github.com/users/sivel/followers',
      following_url: 'https://api.github.com/users/sivel/following{/other_user}',
      gists_url: 'https://api.github.com/users/sivel/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sivel/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sivel/subscriptions',
      organizations_url: 'https://api.github.com/users/sivel/orgs',
      repos_url: 'https://api.github.com/users/sivel/repos',
      events_url: 'https://api.github.com/users/sivel/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sivel/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 187,
    closed_issues: 184,
    state: 'open',
    created_at: '2016-04-12T23:10:49Z',
    updated_at: '2016-09-09T21:46:44Z',
    due_on: null,
    closed_at: null,
  },
  comments: 0,
  created_at: '2016-06-29T21:30:36Z',
  updated_at: '2016-07-11T03:19:37Z',
  closed_at: null,
  pull_request: {
    url: 'https://api.github.com/repos/ansible/ansible/pulls/16510',
    html_url: 'https://github.com/ansible/ansible/pull/16510',
    diff_url: 'https://github.com/ansible/ansible/pull/16510.diff',
    patch_url: 'https://github.com/ansible/ansible/pull/16510.patch',
  },
  body: 'whee',
  score: 1,
}

const issue = {
  url: 'https://api.github.com/repos/cooluser/neatrepo/issues/41',
  repository_url: 'https://api.github.com/repos/kiteco/plugins',
  labels_url: 'https://api.github.com/repos/kiteco/plugins/issues/15/labels{/name}',
  comments_url: 'https://api.github.com/repos/kiteco/plugins/issues/15/comments',
  events_url: 'https://api.github.com/repos/kiteco/plugins/issues/15/events',
  html_url: 'https://github.com/kiteco/plugins/issues/15',
  id: 148539337,
  number: 15,
  title: 'Visual Studio Code Support',
  user: {
    login: 'blackjid',
    id: 228037,
    avatar_url: 'https://avatars.githubusercontent.com/u/228037?v=3',
    gravatar_id: '',
    url: 'https://api.github.com/users/blackjid',
    html_url: 'https://github.com/blackjid',
    followers_url: 'https://api.github.com/users/blackjid/followers',
    following_url: 'https://api.github.com/users/blackjid/following{/other_user}',
    gists_url: 'https://api.github.com/users/blackjid/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/blackjid/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/blackjid/subscriptions',
    organizations_url: 'https://api.github.com/users/blackjid/orgs',
    repos_url: 'https://api.github.com/users/blackjid/repos',
    events_url: 'https://api.github.com/users/blackjid/events{/privacy}',
    received_events_url: 'https://api.github.com/users/blackjid/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [],
  state: 'open',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: null,
  comments: 2,
  created_at: '2016-04-15T02:41:28Z',
  updated_at: '2016-04-22T16:43:08Z',
  closed_at: null,
  body: '',
  score: 1,
}

const task = {
  storageKey: 'pull-163031382',
  id: 163031382,
  type: 'pull',
  title: 'Adds docker-machine module-utils',
  body: 'whee',
  state: 'open',
  createdAt: '2016-06-29T21:30:36Z',
  updatedAt: '2016-07-11T03:19:37Z',
  closedAt: null,
  isPullRequest: true,
  repositoryApiUrl: 'https://api.github.com/repos/ansible/ansible',
  url: 'https://github.com/ansible/ansible/pull/16510',
  number: 16510,
  repository: 'ansible/ansible',
  repositoryOwner: 'ansible',
  repositoryOwnerUrl: 'https://github.com/ansible',
  repositoryOwnerAvatar: 'https://github.com/ansible.png?size=25',
  user: 'jgrowl',
  userUrl: 'https://github.com/jgrowl',
  userAvatar: 'https://github.com/jgrowl.png?size=20',
  userType: 'User',
  apiUrl: 'https://api.github.com/repos/ansible/ansible/pulls/16510',
  comments: 1,
  filterQueries: ['cats'],
  changelog: [],
}

const anotherTask = {
  storageKey: 'issue-55555',
  id: 55555,
  type: 'issue',
  title: 'this is some issue',
  body: 'this is the body',
  state: 'open',
  createdAt: '2016-01-01T00:00:00Z',
  updatedAt: '2016-01-02T00:00:00Z',
  closedAt: null,
  isPullRequest: false,
  repositoryApiUrl: 'https://api.github.com/repos/ansible/ansible',
  url: 'https://github.com/ansible/ansible/issue/1',
  number: 1,
  repository: 'ansible/ansible',
  repositoryOwner: 'ansible',
  repositoryOwnerUrl: 'https://github.com/ansible',
  repositoryOwnerAvatar: 'https://github.com/ansible.png?size=25',
  user: 'jgrowl',
  userUrl: 'https://github.com/jgrowl',
  userAvatar: 'https://github.com/jgrowl.png?size=20',
  userType: 'User',
  apiUrl: 'https://api.github.com/repos/ansible/ansible/issues/1',
  comments: 1,
  filterQueries: ['cats'],
  changelog: [],
}

const notification = {
  id: '1234',
  unread: true,
  reason: 'subscribed',
  updated_at: '2016-08-25T14:16:09Z',
  last_read_at: null,
  subject: {
    title: 'Leave a message at the sound of the beep',
    url: 'https://api.github.com/repos/cooluser/neatrepo/issues/41',
    latest_comment_url: 'https://api.github.com/repos/cooluser/neatrepo/issues/41',
    type: 'Issue',
  },
  repository: {
    id: 9876,
    name: 'neatrepo',
    full_name: 'cooluser/neatrepo',
    owner: {
      login: 'github',
      id: 9919,
      avatar_url: 'https://avatars.githubusercontent.com/u/1234?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/cooluser',
      html_url: 'https://github.com/github',
      followers_url: 'https://api.github.com/users/cooluser/followers',
      following_url: 'https://api.github.com/users/cooluser/following{/other_user}',
      gists_url: 'https://api.github.com/users/cooluser/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/cooluser/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/cooluser/subscriptions',
      organizations_url: 'https://api.github.com/users/cooluser/orgs',
      repos_url: 'https://api.github.com/users/cooluser/repos',
      events_url: 'https://api.github.com/users/cooluser/events{/privacy}',
      received_events_url: 'https://api.github.com/users/cooluser/received_events',
      type: 'Organization',
      site_admin: false,
    },
    private: true,
    html_url: 'https://github.com/cooluser/neatrepo',
    description: 'This is a fun project.',
    fork: false,
    url: 'https://api.github.com/repos/cooluser/neatrepo',
    forks_url: 'https://api.github.com/repos/cooluser/neatrepo/forks',
    keys_url: 'https://api.github.com/repos/cooluser/neatrepo/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/cooluser/neatrepo/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/cooluser/neatrepo/teams',
    hooks_url: 'https://api.github.com/repos/cooluser/neatrepo/hooks',
    issue_events_url: 'https://api.github.com/repos/cooluser/neatrepo/issues/events{/number}',
    events_url: 'https://api.github.com/repos/cooluser/neatrepo/events',
    assignees_url: 'https://api.github.com/repos/cooluser/neatrepo/assignees{/user}',
    branches_url: 'https://api.github.com/repos/cooluser/neatrepo/branches{/branch}',
    tags_url: 'https://api.github.com/repos/cooluser/neatrepo/tags',
    blobs_url: 'https://api.github.com/repos/cooluser/neatrepo/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/cooluser/neatrepo/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/cooluser/neatrepo/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/cooluser/neatrepo/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/cooluser/neatrepo/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/cooluser/neatrepo/languages',
    stargazers_url: 'https://api.github.com/repos/cooluser/neatrepo/stargazers',
    contributors_url: 'https://api.github.com/repos/cooluser/neatrepo/contributors',
    subscribers_url: 'https://api.github.com/repos/cooluser/neatrepo/subscribers',
    subscription_url: 'https://api.github.com/repos/cooluser/neatrepo/subscription',
    commits_url: 'https://api.github.com/repos/cooluser/neatrepo/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/cooluser/neatrepo/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/cooluser/neatrepo/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/cooluser/neatrepo/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/cooluser/neatrepo/contents/{+path}',
    compare_url: 'https://api.github.com/repos/cooluser/neatrepo/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/cooluser/neatrepo/merges',
    archive_url: 'https://api.github.com/repos/cooluser/neatrepo/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/cooluser/neatrepo/downloads',
    issues_url: 'https://api.github.com/repos/cooluser/neatrepo/issues{/number}',
    pulls_url: 'https://api.github.com/repos/cooluser/neatrepo/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/cooluser/neatrepo/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/cooluser/neatrepo/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/cooluser/neatrepo/labels{/name}',
    releases_url: 'https://api.github.com/repos/cooluser/neatrepo/releases{/id}',
    deployments_url: 'https://api.github.com/repos/cooluser/neatrepo/deployments',
  },
  url: 'https://api.github.com/repos/kiteco/plugins/issues/15',
  subscription_url: 'https://api.github.com/notifications/threads/1234/subscription',
}

module.exports = { task, anotherTask, pullRequest, issue, notification }
