const pullRequest = {
  url: 'https://api.github.com/repos/ansible/ansible/issues/16510',
  repository_url: 'https://api.github.com/repos/ansible/ansible',
  labels_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/labels{/name}',
  comments_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/comments',
  events_url: 'https://api.github.com/repos/ansible/ansible/issues/16510/events',
  html_url: 'https://github.com/ansible/ansible/pull/16510',
  id: 163031382,
  number: 16510,
  title: 'Adds docker-machine module-utils',
  user: {
    login: 'jgrowl',
    id: 90719,
    avatar_url: 'https://avatars.githubusercontent.com/u/90719?v=3',
    gravatar_id: '',
    url: 'https://api.github.com/users/jgrowl',
    html_url: 'https://github.com/jgrowl',
    followers_url: 'https://api.github.com/users/jgrowl/followers',
    following_url: 'https://api.github.com/users/jgrowl/following{/other_user}',
    gists_url: 'https://api.github.com/users/jgrowl/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jgrowl/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jgrowl/subscriptions',
    organizations_url: 'https://api.github.com/users/jgrowl/orgs',
    repos_url: 'https://api.github.com/users/jgrowl/repos',
    events_url: 'https://api.github.com/users/jgrowl/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jgrowl/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [
    {
      url: 'https://api.github.com/repos/ansible/ansible/labels/feature_pull_request',
      name: 'feature_pull_request',
      color: '006b75',
    },
    {
      url: 'https://api.github.com/repos/ansible/ansible/labels/new_plugin',
      name: 'new_plugin',
      color: 'bfe5bf',
    },
  ],
  state: 'open',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: {
    url: 'https://api.github.com/repos/ansible/ansible/milestones/8',
    html_url: 'https://github.com/ansible/ansible/milestones/2.2.0',
    labels_url: 'https://api.github.com/repos/ansible/ansible/milestones/8/labels',
    id: 1702615,
    number: 8,
    title: '2.2.0',
    description: '',
    creator: {
      login: 'sivel',
      id: 39340,
      avatar_url: 'https://avatars.githubusercontent.com/u/39340?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/sivel',
      html_url: 'https://github.com/sivel',
      followers_url: 'https://api.github.com/users/sivel/followers',
      following_url: 'https://api.github.com/users/sivel/following{/other_user}',
      gists_url: 'https://api.github.com/users/sivel/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sivel/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sivel/subscriptions',
      organizations_url: 'https://api.github.com/users/sivel/orgs',
      repos_url: 'https://api.github.com/users/sivel/repos',
      events_url: 'https://api.github.com/users/sivel/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sivel/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 187,
    closed_issues: 184,
    state: 'open',
    created_at: '2016-04-12T23:10:49Z',
    updated_at: '2016-09-09T21:46:44Z',
    due_on: null,
    closed_at: null,
  },
  comments: 0,
  created_at: '2016-06-29T21:30:36Z',
  updated_at: '2016-07-11T03:19:37Z',
  closed_at: null,
  pull_request: {
    url: 'https://api.github.com/repos/ansible/ansible/pulls/16510',
    html_url: 'https://github.com/ansible/ansible/pull/16510',
    diff_url: 'https://github.com/ansible/ansible/pull/16510.diff',
    patch_url: 'https://github.com/ansible/ansible/pull/16510.patch',
  },
  body: 'whee',
  score: 1,
}

const task = {
  storageKey: 'pull-163031382',
  id: 163031382,
  type: 'pull',
  title: 'Adds docker-machine module-utils',
  body: 'whee',
  state: 'open',
  createdAt: '2016-06-29T21:30:36Z',
  updatedAt: '2016-07-11T03:19:37Z',
  closedAt: null,
  isPullRequest: true,
  repositoryApiUrl: 'https://api.github.com/repos/ansible/ansible',
  url: 'https://github.com/ansible/ansible/pull/16510',
  number: 16510,
  repository: 'ansible/ansible',
  repositoryOwner: 'ansible',
  repositoryOwnerUrl: 'https://github.com/ansible',
  repositoryOwnerAvatar: 'https://github.com/ansible.png?size=30',
  user: 'jgrowl',
  userUrl: 'https://github.com/jgrowl',
  userAvatar: 'https://github.com/jgrowl.png?size=16',
  userType: 'User',
}

module.exports = { task, pullRequest }
